apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: sast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: managed-csi
