apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data
  namespace: sast
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: sast-azurefile
  resources:
    requests:
      storage: 35Gi
